exclude: ['README.md']

permalink: /:categories/:title/

sass:
    sass_dir: _sass

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
